In [13]:
import numpy as np

In [3]:
arr = np.array([25,41,63,89,78,])
arr

array([25, 41, 63, 89, 78])

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [15]:
1st = [25,41,63,89,78, 58.2,85.52]
arr = np.array(1st)
arr
print(type())

SyntaxError: invalid decimal literal (3308507309.py, line 1)

In [12]:
arr[2]

63

In [9]:
arr[2:4]

array([63, 89])

In [16]:
arr[::-1]

array([78, 89, 63, 41, 25])

In [17]:
arr[-1:-3:-1]

array([78, 89])

In [18]:
arr.ndin

AttributeError: 'numpy.ndarray' object has no attribute 'ndin'

In [19]:
arr.ndim

1

In [20]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
## 1 - 10
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [55]:
arr2 =np.array(([52,63,52,85]
[42,63,52,85]

SyntaxError: incomplete input (326614410.py, line 2)

In [54]:
#[row,column]  #starting_point:ending_point:step_point
arr2[-1,-1]

0.7293889684905679

In [26]:
arr3 = np.arange(60).reshape(12,5)
arr3


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [27]:
arr3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [28]:
arr3.flatten()  #ravel() #reshape

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [31]:
np.random.random((10,2))

array([[0.49215785, 0.40767447],
       [0.34326502, 0.50500752],
       [0.51844462, 0.11329573],
       [0.23454278, 0.15320541],
       [0.49435348, 0.86175279],
       [0.26739656, 0.77056344],
       [0.55897269, 0.83176362],
       [0.22188995, 0.19388634],
       [0.18945045, 0.11452229],
       [0.26454556, 0.50462441]])


#hjhk

In [35]:
np.random.randint(1,5,10)


array([1, 4, 4, 4, 3, 1, 1, 4, 4, 4])

In [36]:
#to replace value
arr[-1]

78

In [37]:
arr[-1] = 100 #to replace value in a array -1 pr
arr

array([ 25,  41,  63,  89, 100])

In [38]:
arr = np.random.randint(1,200,200)
arr

array([ 83,  15, 103, 101, 192, 193, 194,  16, 115,  65, 106, 148,  39,
        21,  48, 154,  17,  70, 125, 182,  53,   4,  17,   5, 168, 101,
        99,  61, 197,  93, 133,   1, 186, 110, 135, 165,  85,  13, 108,
        64, 198,  32,  95, 110, 114, 167,  66,  54, 157, 124, 118, 140,
        23, 124,  39,  89,  37, 129,  13,  53, 156,  12, 175, 123,  19,
        19,  67,  19,  24,  60, 185, 146,  35,  55, 182,  11,   4, 134,
        97, 117, 112,  71, 105, 154, 144, 100, 100, 161, 114, 116,   8,
       181, 176,  94, 150,  72, 192, 158, 160, 145, 118, 183,  92, 106,
        45,  74,  54, 105,  72,  48,  47,  46,  11,  74,  78, 155,   6,
       142, 183, 123,  63, 194, 187,  28,  77,  98, 149, 123,  94, 161,
        87,  10, 138,  86,  17, 157,   1,  28,  94, 143,  30, 173, 160,
       121, 135, 187,  33,  85, 112, 173, 120, 145, 159, 178,  16,   2,
        66, 187, 167,  30, 124, 113, 152,  80, 179,  93, 100,  69, 103,
       172, 137, 115,  56,  13, 140,  26,  75,  97,  20,  42,   

In [39]:
arr<100

array([ True,  True, False, False, False, False, False,  True, False,
        True, False, False,  True,  True,  True, False,  True,  True,
       False, False,  True,  True,  True,  True, False, False,  True,
        True, False,  True, False,  True, False, False, False, False,
        True,  True, False,  True, False,  True,  True, False, False,
       False,  True,  True, False, False, False, False,  True, False,
        True,  True,  True, False,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True, False,  True,  True, False,  True, False, False,
        True, False, False, False, False, False, False, False, False,
        True, False, False,  True, False,  True, False, False, False,
       False, False, False,  True, False,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False, False, False,  True, False, False,  True,  True,  True,
       False, False,

In [40]:
arr[arr<100]

array([83, 15, 16, 65, 39, 21, 48, 17, 70, 53,  4, 17,  5, 99, 61, 93,  1,
       85, 13, 64, 32, 95, 66, 54, 23, 39, 89, 37, 13, 53, 12, 19, 19, 67,
       19, 24, 60, 35, 55, 11,  4, 97, 71,  8, 94, 72, 92, 45, 74, 54, 72,
       48, 47, 46, 11, 74, 78,  6, 63, 28, 77, 98, 94, 87, 10, 86, 17,  1,
       28, 94, 30, 33, 85, 16,  2, 66, 30, 80, 93, 69, 56, 13, 26, 75, 97,
       20, 42,  1, 83, 92, 62, 41, 79, 29, 61, 50, 61, 27, 49, 88])

In [11]:
arr[arr<100].shape

NameError: name 'arr' is not defined

In [14]:
[[[1,2,3],
  [4,5,6]],
 [[1,2,3],
  [4,5,6]],
 [[1,2,3],
  [4,5,6]],
 [[1,2,3],
  [4,5,6]]]

arr = np.array([[[1,2,3],
  [4,5,6]],
 [[1,2,3],
  [4,5,6]],
 [[1,2,3],
  [4,5,6]],
 [[1,2,3],
  [4,5,6]]])
arr


array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [16]:
arr.ndim

3

In [17]:
arr.shape

(4, 2, 3)

In [18]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr[1,0,2]

3

In [22]:
a =arr[1,0, :][2]

In [27]:
a =arr[1,0,:]

In [28]:
a[:: -1]

array([3, 2, 1])

In [29]:
arr[2,1,1:]  #1: start from 1 to all column

array([5, 6])

In [30]:
arr[1,2,3]
   [4,5,6],
    

IndentationError: unexpected indent (3636078372.py, line 2)

In [34]:
arr[:,0, :]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [56]:
arr1 = np.random.random((3,2))
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [36]:
arr2.shape

(3, 2)

In [38]:
arr2.T #Transpose

array([[0.58505468, 0.24206747, 0.33024291],
       [0.50712171, 0.32014445, 0.72938897]])

In [42]:
arr2.shape

(3, 2)

In [58]:
arr1.shape

(3, 2)

In [57]:
np.concatenate((arr1,arr2),axis=1)

array([[0.60311513, 0.47540599, 0.58505468, 0.50712171],
       [0.69676497, 0.75786762, 0.24206747, 0.32014445],
       [0.57959691, 0.36727551, 0.33024291, 0.72938897]])

In [61]:
arr= np.arange[10]
arr 

TypeError: 'builtin_function_or_method' object is not subscriptable

In [62]:
arr.mean() #min,max,sum

3.5

In [63]:
arr.max()

6

In [65]:
#multiply of 2d & id array
arr1 = np.array([[1,2,3]]),([[4,5,6]])


arr1

(array([[1, 2, 3]]), [[4, 5, 6]])

In [67]:
arr = np.array([4,5,6,7,1,8])
arr

array([4, 5, 6, 7, 1, 8])

In [69]:
arr1 = arr2

In [71]:
arr.sort() #sorting array

In [72]:
arr

array([1, 4, 5, 6, 7, 8])

In [76]:
arr.argsort() #

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [77]:
arr.argmin()

0

In [78]:
arr.argmax()

5

In [80]:
arr.argmin()

0